export default class SchoolNameServiceProvider {

    /**
     * Get a list of school names
     * https://en.wikipedia.org/wiki/List_of_universities_in_Canada
     * @returns {string[]}
     */
    static getList() {
        return [
            "Acadia University",
            "Algoma University",
            "Athabasca University",
            "Atlantic School of Theology",
            "Bishop's University",
            "Booth University College",
            "Brandon University",
            "Brock University",
            "Canadian Mennonite University",
            "Cape Breton University",
            "Capilano University",
            "Carleton University",
            "Concordia University",
            "Crandall University",
            "Dalhousie University",
            "Dominican University College",
            "École de technologie supérieure",
            "École nationale d'administration publique",
            "École Polytechnique de Montréal",
            "Emily Carr University of Art and Design",
            "Fairleigh Dickinson University",
            "First Nations University of Canada",
            "HEC Montréal",
            "Huron University College",
            "Institut national de la recherche scientifique",
            "Kingswood University",
            "Kwantlen Polytechnic University",
            "Lakehead University",
            "Laurentian University",
            "MacEwan University",
            "McGill University",
            "McMaster University",
            "Memorial University of Newfoundland",
            "Mount Allison University",
            "Mount Royal University",
            "Mount Saint Vincent University",
            "New York Institute of Technology",
            "Nipissing University",
            "NSCAD University",
            "OCAD University",
            "Queen's University",
            "Quest University",
            "Redeemer University College",
            "Royal Military College of Canada",
            "Royal Roads University",
            "Ryerson University",
            "Saint Francis Xavier University",
            "Saint Mary's University",
            "Saint Paul University",
            "Simon Fraser University",
            "St. Stephen's University",
            "St. Thomas University",
            "The King's University",
            "Thompson Rivers University",
            "Trent University",
            "Trinity Western University",
            "Tyndale University College",
            "Université de Moncton",
            "Université de Montréal",
            "Université de Saint-Boniface",
            "Université de Sherbrooke",
            "Université du Québec à Chicoutimi",
            "Université du Québec à Montréal",
            "Université du Québec à Rimouski",
            "Université du Québec à Trois-Rivières",
            "Université du Québec en Abitibi-Témiscamingue",
            "Université du Québec en Outaouais",
            "Université Laval",
            "Université Sainte-Anne",
            "University Canada West",
            "University College of the North",
            "University of Alberta",
            "University of British Columbia",
            "University of Calgary",
            "University of Fredericton",
            "University of Guelph",
            "University of King's College",
            "University of Lethbridge",
            "University of Manitoba",
            "University of New Brunswick",
            "University of Northern British Columbia",
            "University of Ontario Institute of Technology",
            "University of Ottawa",
            "University of Prince Edward Island",
            "University of Regina",
            "University of Saskatchewan",
            "University of the Fraser Valley",
            "University of Toronto",
            "University of Toronto Scarborough",
            "University of Toronto Mississauga",
            "University of Victoria",
            "University of Waterloo",
            "University of Western Ontario",
            "University of Windsor",
            "University of Winnipeg",
            "Vancouver Island University",
            "Wilfrid Laurier University",
            "York University",
        ];
    }
}
